#!/bin/bash

#PBS -q scavenger
#PBS -A scavenger
#PBS -o log
#PBS -V
#PBS -j oe
#PBS -N parse_database_ancestral_allele
#PBS -l nodes=1:ppn=1,mem=5G
#PBS -t 1-127

#-q analysis
#-A proj-fy0006
#-l walltime=13:00:00:00

cd $PBS_O_WORKDIR

# PBS_ARRAYID

t1=$(date +%s)

incr=1
istart=$[(PBS_ARRAYID-1)*incr+1]
iend=$[PBS_ARRAYID*incr]

binlist=../data/proc/bin_id_list/SNPAncestralAllele.bin.list
for bin in $(cat $binlist | awk 'NR>='$istart' && NR<='$iend''); do
    python3 parse_database_ancestral_allele.py $bin
done



t2=$(date +%s)
dt=$[t2-t1]
echo "% Job $PBS_ARRAYID is done in $(date -ud @$dt +%j:%T | awk -F\: '{printf("%03d:%02d:%02d:%02d\n",$1-1,$2,$3,$4)}')"
